name: latex-pdf-generator
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v6
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: notes-08052026
          latexmk_use_xelatex: true
      - name: Upload PDF
        uses: actions/upload-artifact@v6
        with:
          name: PDF
          path: notes-08052026.pdf