name: latex-pdf-generator
on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  tex-job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ github.workspace }}/Scripts
    steps:
      - uses: actions/checkout@main
        with:
          token: ${{ secrets.PERMIT_TOKEN }}
      - name: Make the scripts executable
        run: chmod +x generate-pdf.sh
      - name: Run the script
        run: ./generate-pdf.sh
      - name: Upload The Pdf
        uses: actions/upload-artifact@v4
        with:
          name: reading-notes
          path: ${{ github.workspace }}/reading-notes/reading-notes/notes-08052026
          retention-days: 5